flags: {}
packages:
- '.'
extra-deps:
 - git: https://github.com/remeike/fn-monadic
   commit: 2365dd816915548833b453c3d53f3addedbb3f16
   subdirs:
    - fn-monadic
 - git: https://github.com/remeike/tk
   commit: ba78d160e86f41bd1f029e039f58b1456006663f

resolver: lts-20.26
